= Installation
:description: Install Longhorn on Kubernetes
:doctype: book
:current-version: {page-origin-branch}

NOTE: This quick installation guide uses some configurations which are not for production usage.
Please see xref:deploy/best-practices.adoc[Best Practices] for how to configure Longhorn for production usage.

Longhorn can be installed on a Kubernetes cluster in several ways:

* link:./install-with-rancher[Rancher catalog app]
* link:./install-with-kubectl/[kubectl]
* link:./install-with-helm/[Helm]
* link:./install-with-fleet/[Fleet]
* link:./install-with-flux/[Flux]
* link:./install-with-argocd/[ArgoCD]

To install Longhorn in an air gapped environment, refer to xref:deploy/install/install/airgap.adoc[this section.]

For information on customizing Longhorn's default settings, refer to xref:deploy/advanced-resources/deploy/customizing-default-settings.adoc[this section.]

For information on deploying Longhorn on specific nodes and rejecting general workloads for those nodes, refer to the section on xref:deploy/advanced-resources/deploy/taint-toleration.adoc[taints and tolerations.]