name: Test deployment

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: [opened, edited, synchronize, reopened]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Antora and dependencies
        run: make environment
      - name: Generate Site
        run: |
          npx antora --stacktrace \
            --log-file local-build.log \
            --log-format=pretty \
            --log-level=info \
            --log-failure-level=warn \
            playbook-local.yml 2>&1 | tee local-build.log 2>&1
            BUILD_STATUS=${PIPESTATUS[0]}
            if grep "INFO (asciidoctor)" local-build.log; then
              BUILD_STATUS=1
            fi
            echo "BUILD_STATUS=$BUILD_STATUS" >> $GITHUB_ENV
      - name: Check for build errors
        run: |
          echo ${{ env.BUILD_STATUS }}
          if [ ${{ env.BUILD_STATUS }} -eq "0" ]; then
            exit 0
          else
            cat local-build.log
            exit 1
          fi
